---
#- hosts: worker1
  
#  tasks:
#  - name: initializing swarm
#    script: swarm.sh "146.193.41.141:2375"

- hosts: worker3

  tasks:
  - name: initializing swarm
    script: swarm.sh "146.193.41.143:2375"

- hosts: worker4
  
  tasks:
  - name: initializing swarm
    script: swarm.sh "146.193.41.144:2375"

#- hosts: worker5
  
#  tasks:
 # - name: initializing swarm
  #  script: swarm.sh "146.193.41.145:2375"

#- hosts: worker6
  
 # tasks:
  #- name: initializing swarm
  #  script: swarm.sh "146.193.41.146:2375"
